Use svg logo instead of png for better quality
dotnet/nuget-trends pull request #146
Opened 2021-05-13 20:26 UTC by Tyrrrz

Currently, the logo looks very blurry because it's a resized PNG image:

![image](https://user-images.githubusercontent.com/1935960/118183255-bf6b4a00-b3ee-11eb-8ef1-9ec20c2fe512.png)

SVG should look better when resized. Converted using a tool, so it's not very optimized.

2021-05-13 20:29 UTC, bruno-garcia commented
Thanks @Tyrrrz.. Since this is something the eyes can see, I'll defer to @joaopgrassi

2021-05-14 12:50 UTC, Tyrrrz commented
Updated: running `ng serve` failed with:

```
An unhandled exception occurred: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
   -> The base directory (absolute path!) for resolving the `entry` option. If `output.pathinfo` is set, the included pathinfo is shortened to this directory.
 - configuration.module.rules[12].include should be one of these:
   RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? } | [RegExp | string | function | [(recursive)] | object { and?, exclude?, include?, not?, or?, test? }]
   -> One or multiple rule conditions
   Details:
    * configuration.module.rules[10].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[1]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\ngx-toastr\\toastr.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[2]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\font-awesome\\css\\font-awesome.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[3]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\colors.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[4]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\styles.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[1]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\ngx-toastr\\toastr.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[2]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\font-awesome\\css\\font-awesome.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[3]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\colors.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[10].include[4]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\styles.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[1]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\ngx-toastr\\toastr.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[2]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\font-awesome\\css\\font-awesome.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[3]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\colors.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[4]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\styles.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[1]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\ngx-toastr\\toastr.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[2]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\font-awesome\\css\\font-awesome.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[3]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\colors.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[11].include[4]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\styles.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[1]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\ngx-toastr\\toastr.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[2]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\font-awesome\\css\\font-awesome.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[3]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\colors.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[4]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\src\\styles.scss" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.module.rules[12].include[0]: The provided value "f:\\Projects\\Softdev\\!Contrib\\nuget-trends\\src\\NuGetTrends.Web\\Portal\\node_modules\\bulma\\css\\bulma.min.css" contains exclamation mark (!) which is not allowed because it's reserved for loader syntax.
    * configuration.mod [...]

2021-05-14 12:56 UTC, joaopgrassi commented
Hum strange no idea what is that error. As the CI build works. Did you restore the pages using yarn or npm? We use yarn, so that might be it?

About the logo, thanks. The logo initially came from a freelancer I hired from Fiverr, but we had help of another contributor in the past that got us into the version that is today.

I looked locally and although it's better, there is some rough edges:
SVG:
![image](https://user-images.githubusercontent.com/5938087/118273553-59e98d00-b4c4-11eb-968a-6cfadbe9e885.png)

Wheres the older is at least smooth (I agree it's blurry as hell..)
PNG
![image](https://user-images.githubusercontent.com/5938087/118273633-74bc0180-b4c4-11eb-8fdb-f642896e5621.png)

So not sure what is best. My OCD got triggered by the rough edges almost immediately :sweat_smile:

2021-05-14 14:51 UTC, Tyrrrz commented
Actually, another option would probably be just to pre-resize the png file with a better resize algorithm.

For example this is the image resized to width=450, a lot less blurry than when it's resized at runtime

![logo-inverted](https://user-images.githubusercontent.com/1935960/118288289-1faeca00-b489-11eb-87eb-f020f3d4bbac.png)

2021-05-14 15:24 UTC, joaopgrassi commented
Cool, if that improves it then I'm good with it :). If you want to push this new resized one then we can see how it looks.

2021-05-15 20:34 UTC, Tyrrrz commented
Pushed an update

2021-05-16 09:03 UTC, joaopgrassi commented
Ok I took a look, seems a bit better? Maybe my eye sight is just bad lol

![image](https://user-images.githubusercontent.com/5938087/118391760-4cecab00-b636-11eb-83b5-b5b0b13793bf.png)

2021-05-16 09:07 UTC, joaopgrassi requested changes

2021-05-16 09:07 UTC, joaopgrassi commented on src/NuGetTrends.Web/Portal/src/app/app.component.html
> +            <a [routerLink]="['/']"><img src="../assets/images/logo-inverted-400.png" width="400" alt="NuGet Trends brand logo"></a>
I guess now we can remove this.

2021-05-16 09:07 UTC, joaopgrassi commented on src/NuGetTrends.Web/Portal/src/app/core/footer/footer.component.html
> +          <img src="../../assets/images/logo-inverted-350.png" width="350" alt="NuGet Trends brand logo">
Here as well

2021-05-16 17:58 UTC, Tyrrrz commented
> Ok I took a look, seems a bit better? Maybe my eye sight is just bad lol
> 
> ![image](https://user-images.githubusercontent.com/5938087/118391760-4cecab00-b636-11eb-83b5-b5b0b13793bf.png)

I don't know why, but in your screenshot neither of them look blurry. Here's how the current version looks for me (used Edge specifically to make sure it's not a browser issue):

![image](https://user-images.githubusercontent.com/1935960/118407446-9b4d7a00-b635-11eb-82ea-7afcd03673a7.png)

You can see in my screenshot it's noticeably more blurry than in yours for some reason.

2021-05-16 18:00 UTC, Tyrrrz commented on src/NuGetTrends.Web/Portal/src/app/app.component.html
> +            <a [routerLink]="['/']"><img src="../assets/images/logo-inverted-400.png" width="400" alt="NuGet Trends brand logo"></a>
```suggestion
            <a [routerLink]="['/']"><img src="../assets/images/logo-inverted-400.png" alt="NuGet Trends brand logo"></a>
```

2021-05-16 18:01 UTC, Tyrrrz commented on src/NuGetTrends.Web/Portal/src/app/core/footer/footer.component.html
> +          <img src="../../assets/images/logo-inverted-350.png" width="350" alt="NuGet Trends brand logo">
```suggestion
          <img src="../../assets/images/logo-inverted-350.png" alt="NuGet Trends brand logo">
```

2021-05-16 18:21 UTC, joaopgrassi approved these changes
Damn it does look awful on Chrome, my gosh! Sorry, I'm used to Firefox didn't even consider this case. It looks amazing now! Thanks a lot!

2021-05-16 18:29 UTC, merged

2021-05-16 18:43 UTC, bruno-garcia commented
I'm glad the commits were not `wip`:

![image](https://user-images.githubusercontent.com/1633368/118408804-1d00d000-b655-11eb-9eec-273be0c3d8c3.png)

:)
Thanks for contributing @Tyrrrz

2021-05-16 18:55 UTC, joaopgrassi commented
Oops..

2021-05-16 19:01 UTC, Tyrrrz commented
> I'm glad the commits were not `wip`:

I promise to fix this next time ;)

2021-05-16 19:01 UTC, Tyrrrz commented
> Damn it does look awful on Chrome, my gosh! Sorry, I'm used to Firefox didn't even consider this case. It looks amazing now! Thanks a lot!

Never considered Chrome to be so bad at resizing images :D